version: '3.8'

services:
  activemq:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
      - ARTEMIS_MIN_MEMORY=512M
      - ARTEMIS_MAX_MEMORY=2G
